[package]
name = "fixcclp3"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
serde_json.workspace = true
regex = "1"
chipdat = { path = "../../chipdat" }
chipty = { path = "../../chipty" }
