[package]
name = "levelquery"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
dataview.workspace = true
chipty = { path = "../../chipty" }
chipdat = { path = "../../chipdat" }
cvmath.workspace = true
serde_json.workspace = true
pupil = "1.0"
