[package]
name = "levelquery"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
dataview = "1.0"
chipty = { path = "../../chipty" }
cvmath.workspace = true
serde_json.workspace = true
