[package]
name = "chipundat"
version = "0.1.0"
edition = "2021"

[dependencies]
chipty = { path = "../../chipty" }
chipdat = { path = "../../chipdat" }
clap.workspace = true
serde_json.workspace = true
