[package]
name = "colorkey"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
dataview.workspace = true
cvmath.workspace = true
serde_json.workspace = true
ini_core.workspace = true
png.workspace = true
