[package]
name = "replayfix"
version = "0.1.0"
edition = "2021"

[dependencies]
chipcore = { path = "../../chipcore" }
chipty = { path = "../../chipty" }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
rayon = "1.10"
