[package]
name = "fixlevel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
serde_json.workspace = true
chipdat = { path = "../../chipdat" }
chipty = { path = "../../chipty" }
