[package]
name = "extract"
version = "0.1.0"
edition = "2021"

[dependencies]
chipdat = { path = "../../chipdat" }
clap.workspace = true
dataview.workspace = true
chipty = { path = "../../chipty" }
cvmath.workspace = true
serde_json.workspace = true
